export const ROUTE_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  OAUTH2_CALLBACK: "/oauth2/callback",
  DASHBOARD: "/dashboard",
  MY_ACCOUNT: "/my-account",
  PAPERS: "/papers",
  PAPER_DETAIL: "/papers/:paperId",
  paperDetail: (paperId) => `/papers/${paperId}`,
  TRENDS: "/trends",
  TOPICS: "/topics",
  JOURNALS: "/journals",
  KEYWORDS: "/keywords",
  BOOKMARKS: "/bookmarks",
  FOLLOWING: "/following",
  NOTIFICATIONS: "/notifications",
  REPORTS: "/reports",
  ADMIN: "/admin",
};
